services:
  - name: docker:stable
    alias: docker


stages:          # List of stages for jobs, and their order of execution
  - test
  - build

test go:
  stage: test
  image: golang
  allow_failure: false
  script:
    - cd src
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)
  rules:
    - changes:
        - Dockerfile
        - src/**
        - .gitlab-ci.yml
      when: always

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  allow_failure: false
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  rules:
    - changes:
        - Dockerfile
        - src/**
        - .gitlab-ci.yml
      when: always